name: Deploy to GCP VM

on:
  push:
    branches:
      - main  # Cambia por "master" si tu rama principal se llama así

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to GCP VM
        run: |
          ssh -o StrictHostKeyChecking=no sebjardo@34.121.79.94 << 'EOF'
            cd ~/project-final/fuudi || exit 1
            git pull origin main || exit 1
            npm install || exit 1
            npm run build || exit 1
            sudo rm -rf /var/www/html/* || exit 1
            sudo cp -r build/* /var/www/html/ || exit 1
            echo "🚀 Deploy completo"
          EOF